import{useEffect,useRef,useState}from"react";import{business as b}from"./business.js";
function Reveal({children,delay=0,className=""}){const ref=useRef(null),[show,setShow]=useState(false);useEffect(()=>{const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setShow(true);o.disconnect()}},{threshold:.12});if(ref.current)o.observe(ref.current);return()=>o.disconnect()},[]);return <div ref={ref} style={{"--delay":delay+"ms"}} className={"reveal "+(show?"show ":"")+className}>{children}</div>}
function Arrow(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-4 w-4"><path d="M4 12h15m-6-7 7 7-7 7"/></svg>}
export default function App(){const tel=b.phone.split("/")[0].replace(/[^0-9+]/g,""),wa=tel.replace(/\D/g,"").replace(/^0/,"27");return <main className="min-h-screen overflow-hidden bg-ink text-white">
<div className="notice"><i/>Independent concept preview · Not commissioned or approved by {b.company}</div>
<header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><a href="#top" className="flex items-center gap-3"><span className="mark">P</span><b className="text-sm tracking-wide">{b.company}</b></a><nav className="hidden gap-8 text-sm text-white/60 md:flex"><a href="#services">Services</a><a href="#contact">Contact</a></nav><a className="pill small" href={"tel:"+tel}>Call now <Arrow/></a></header>
<section id="top" className="hero mx-auto grid max-w-7xl items-center gap-12 px-6 pb-24 pt-10 md:grid-cols-2 md:py-24">
<div className="glow"/><div className="relative z-10"><Reveal><div className="kicker"><span/> {b.industry} · {b.city}, South Africa</div></Reveal><Reveal delay={80}><h1 className="mt-7 max-w-2xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-6xl lg:text-7xl">Good work starts with a <em>clear connection.</em></h1></Reveal><Reveal delay={160}><p className="mt-7 max-w-lg text-base leading-7 text-white/60">A simple way to explore plumbing services and contact {b.company} about your next project.</p></Reveal><Reveal delay={230}><div className="mt-9 flex flex-wrap gap-3"><a href={"tel:"+tel} className="pill">Call for an enquiry <Arrow/></a><a href={"https://wa.me/"+wa} target="_blank" rel="noreferrer" className="pill quiet">WhatsApp</a></div></Reveal><Reveal delay={300}><div className="mt-9 text-sm text-white/45">⌖ &nbsp;{b.city} and surrounds</div></Reveal></div>
<Reveal delay={120}><div className="art"><div className="art-meta">FIELD NOTE / PLUMBING <span>✳</span></div><div className="pipe p1"/><div className="pipe p2"/><div className="pipe p3"/><div className="joint j1"/><div className="joint j2"/><div className="drop"/><div className="art-caption"><small>LOCAL SERVICE CONCEPT</small><b>Practical help, one conversation away.</b></div></div></Reveal>
</section>
<section id="services" className="mx-auto max-w-7xl px-6 py-20 md:py-28"><Reveal><div className="section-head"><div><div className="kicker">WHAT YOU CAN ASK ABOUT</div><h2>Plumbing, made easier to navigate.</h2></div><p>A concept layout that keeps service information and contact options close at hand.</p></div></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3">{["Installations","Repairs","Maintenance"].map((x,i)=><Reveal key={x} delay={i*90}><article className="card"><small>0{i+1}</small><div className="bars"><i/><i/><i/></div><h3>{x}</h3><p>A clear place to introduce {x.toLowerCase()} enquiries and help visitors reach the business.</p><a href="#contact">Make an enquiry <Arrow/></a></article></Reveal>)}</div></section>
<section className="mx-auto max-w-7xl px-6 pb-24"><Reveal><div className="statement"><div className="kicker">A BETTER FIRST IMPRESSION</div><h2>From first question<br/><em>to next step.</em></h2><p>This sample shows one possible way for {b.company} to present its plumbing services online.</p><a className="pill" href="#contact">Get in touch <Arrow/></a><i className="rings"/></div></Reveal></section>
<section id="contact" className="mx-auto grid max-w-7xl gap-10 px-6 pb-24 md:grid-cols-2 md:items-center"><Reveal><div className="kicker">CONTACT</div><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Start with a conversation.</h2><p className="mt-5 max-w-md leading-7 text-white/55">Use the public business contact details shown in the City of Cape Town plumber register.</p></Reveal><Reveal delay={100}><div className="contact"><a href={"tel:"+tel}><span>PHONE</span><b>{b.phone}</b><Arrow/></a>{b.email&&<a href={"mailto:"+b.email}><span>EMAIL</span><b>{b.email}</b><Arrow/></a>}<small>Concept page · Verify contact details before publishing as an official business site.</small></div></Reveal></section>
<footer className="mx-auto flex max-w-7xl flex-col gap-3 border-t border-white/10 px-6 py-8 text-xs text-white/40 md:flex-row md:justify-between"><span>© {new Date().getFullYear()} {b.company} · Independent concept preview</span><span>Built by <b className="text-white/70">TNO Digital Services</b></span></footer></main>}